name: 🐍 Contribution Snake

on:
  schedule:
    - cron: "17 0 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    name: Generate contribution snake
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: vishesh1916
          outputs: |
            dist/github-snake.svg?palette=github-light&color_snake=%2300FF9C
            dist/github-snake-dark.svg?palette=github-dark&color_snake=%2300FF9C
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish generated files
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
          keep_files: true
          commit_message: "chore: update contribution snake"
